/*
版本信息:1.0
创建者	:XYU
功能描述:港股通（沪和深）交易数据报表
加载类型:全量加载
源		 表：
	NSODATA.CSDC_INOVT_TRAD -- CSDC_J4009_交易_创新_成交表
	NSODATA.CSDC_INOVT_STM_EXCHG_RT -- CSDC_J4004_交易_创新_港股通结算汇率表
	NSODATA.CSDC_INTG_SEC_ACCT -- CSDC_J0001_信息_整合_证券账户表
	NSODATA.CSDC_HKST_TRAD_CLR_DTL_TB -- CSDC_J6001_港股通交易清算明细表
	NSODATA.CSDC_INTG_SEC_ACCT -- CSDC_J0001_信息_整合_证券账户表

目	标	表:	nsSMSMart.SMS_QRY_2_HKST_TRAD_RPT	-- 港股通（沪和深）交易数据报表
频		 度:D:日
创建日期:	2018-01-24
修改历史:
修改人	修改日期	修改内容
*/

DELETE FROM ${NSSMSMART}.SMS_QRY_2_HKST_TRAD_RPT
WHERE STAT_DATE = '${TXDATE}'
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO ${NSSMSMART}.SMS_QRY_2_HKST_TRAD_RPT
SELECT ---港股通交易，区间参加港股通交易账户数
'${TXDATE}' AS STAT_DATE
,'0' AS SEC_EXCH_CDE
,A1.INVST_SORT AS INVST_CLSF
-- ,CASE 
-- 	 WHEN A1.INVST_SORT IN ('235') THEN '证券投资基金'									
-- 	 WHEN A1.INVST_SORT IN ('231') THEN '证券公司自营'
-- 	 WHEN A1.INVST_SORT IN ('239') THEN 'QFII'
-- 	 WHEN A1.INVST_SORT IN ('233') THEN '信托公司'
-- 	 WHEN A1.INVST_SORT IN ('110') THEN '自然人'									
-- 	 WHEN A1.INVST_SORT IN ('236') THEN '社保基金'									
-- 	 WHEN A1.INVST_SORT IN ('234') THEN '保险公司'
-- 	 WHEN A1.INVST_SORT IN ('232') THEN '证券公司集合理财'									
-- 	 WHEN A1.INVST_SORT IN ('238') THEN '企业年金'									
--      WHEN A1.INVST_SORT IN ('23A') THEN '基金专户理财'
-- 	 WHEN A1.INVST_SORT IN ('23C') THEN 'RQFII'
-- 	 ELSE '一般机构'
-- 	 END AS INVST_CLSF
,SUM(A2.BUY_AMT) AS BUY_AMT
,SUM(A2.SELL_AMT) AS SAL_AMT
,SUM(A2.BUY_AMT-A2.SELL_AMT) AS TRAD_NET_AMT
FROM
(SELECT 
TRAD_DATE
,SEC_CDE
,SEC_ACCT
,SUM(CASE WHEN TRAD_INDC = 'B' THEN CAST((TRAD_VOL * TRAN_PRC * BUY_EXCH_RATE) AS DECIMAL(18,2)) ELSE 0.00 END) AS BUY_AMT
,SUM(CASE WHEN TRAD_INDC = 'S' THEN CAST((TRAD_VOL * TRAN_PRC * SAL_EXCH_RATE) AS DECIMAL(18,2)) ELSE 0.00 END) AS SELL_AMT
FROM ${NSOVIEW}.CSDC_INOVT_TRAD A1
     ,${NSOVIEW}.CSDC_INOVT_STM_EXCHG_RT B1
WHERE TRAD_DATE = '${TXDATE}'
AND A1.TRAD_DATE=B1.APPLY_DATE
GROUP BY 1,2,3
)A2
INNER JOIN
(SELECT 								
		SEC_ACCT								
        ,INVST_SORT										
        FROM 										
		${NSOVIEW}.CSDC_INTG_SEC_ACCT    							
        WHERE  S_DATE <= '${TXDATE}' AND E_DATE > '${TXDATE}'	 									
         AND INVST_SORT <>'   '
		 AND MKT_SORT = '0') A1	      		
ON A2.SEC_ACCT=A1.SEC_ACCT
GROUP BY A1.INVST_SORT

UNION ALL

SELECT -- 港股通-深圳
'${TXDATE}' AS STAT_DATE
,'1' AS SEC_EXCH_CDE
,A1.INVST_SORT AS INVST_CLSF
-- ,CASE 
-- 	 WHEN A1.INVST_SORT IN ('235') THEN '证券投资基金'									
-- 	 WHEN A1.INVST_SORT IN ('231') THEN '证券公司自营'
-- 	 WHEN A1.INVST_SORT IN ('239') THEN 'QFII'
-- 	 WHEN A1.INVST_SORT IN ('233') THEN '信托公司'
-- 	 WHEN A1.INVST_SORT IN ('110') THEN '自然人'									
-- 	 WHEN A1.INVST_SORT IN ('236') THEN '社保基金'									
-- 	 WHEN A1.INVST_SORT IN ('234') THEN '保险公司'
-- 	 WHEN A1.INVST_SORT IN ('232') THEN '证券公司集合理财'									
-- 	 WHEN A1.INVST_SORT IN ('238') THEN '企业年金'									
--      WHEN A1.INVST_SORT IN ('23A') THEN '基金专户理财'
-- 	 WHEN A1.INVST_SORT IN ('23C') THEN 'RQFII'
-- 	 ELSE '一般机构'
-- 	 END AS INVST_CLSF
,SUM(A2.BUY_AMT) AS BUY_AMT
,SUM(A2.SELL_AMT) AS SAL_AMT
,SUM(A2.BUY_AMT-A2.SELL_AMT) AS TRAD_NET_AMT
FROM
(
SELECT 
  TRAD_DATE
  ,SHDR_ACCT
  ,SUM(CASE WHEN TRAD_VOL>0 THEN CAST((TRAD_VOL*TRAN_PRC*EXCH_RT) AS DECIMAL(18,2)) ELSE 0.00 END) AS BUY_AMT 
  ,SUM(CASE WHEN TRAD_VOL<0 THEN CAST((TRAD_VOL*TRAN_PRC*EXCH_RT) AS DECIMAL(18,2)) ELSE 0.00 END) AS SELL_AMT
FROM
   ${NSOVIEW}.CSDC_HKST_TRAD_CLR_DTL_TB  ---CSDC_J6001_交易_港股通交易清算明细表
WHERE
  TRAD_DATE  = '${TXDATE}'
GROUP BY 1,2
)A2
INNER JOIN
(SELECT 								
		SEC_ACCT								
        ,INVST_SORT										
        FROM 										
		${NSOVIEW}.CSDC_INTG_SEC_ACCT    							
        WHERE  S_DATE <= '${TXDATE}' AND E_DATE > '${TXDATE}'	 									
         AND INVST_SORT <>'   '
		 AND MKT_SORT = '1') A1	      		
ON A2.SHDR_ACCT=A1.SEC_ACCT
GROUP BY A1.INVST_SORT
;
.IF ERRORCODE <> 0 THEN .QUIT 12;

.QUIT

