/*
版本信息:1.0
创建者	:XYU
功能描述:质押库面值与标准券余额报表
加载类型:全量加载
源		 表：
	NSODATA.CSDC_H_OTH_HLD_BAL -- CSDC_J1032_沪_其他持有余额表
	NSODATA.CSDC_INTG_SEC_INFO -- CSDC_J0013_整合_证券信息表
	NSODATA.CSDC_H_BPR_STD_STK_RT -- CSDC_J1041_沪_债券质押式回购标准券比例表
	NSODATA.CSDC_S_BOND_PLG_HIS -- CSDC_J2049_深_债券质押历史
	NSODATA.CSDC_S_SEC_CNVTR_HIS -- CSDC_J2093_深_证券折算率历史
目	标	表:	nsSMSMart.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT	-- 质押库面值与标准券余额报表
频		 度:D:日
创建日期:	2018-01-24
修改历史:
修改人	修改日期	修改内容
*/

delete from ${NSSMSMART}.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT
where stat_date = '${TXDATE}'
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

INSERT INTO ${NSSMSMART}.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT
--沪市
SELECT 
	'${TXDATE}' AS STAT_DATE
	,SUBSTR(CAST(1000000+A1.SEC_CDE AS CHAR(7)),2) AS SEC_CDE
	,A1.SEC_NAME
	,SUM(A1.PLG_VOL)/1E8 AS BOND_PAR_VAL
	,SUM(A1.PLG_VOL*A2.CRENT_RATE)/1E8 AS STD_STK_AMT
FROM
	(
	SELECT 
		T1.SEC_CDE
		,T2.SEC_NAME
		,SUM(VOL1) AS PLG_VOL
	FROM  
		${NSOVIEW}.CSDC_H_OTH_HLD_BAL T1
	
		INNER JOIN
			
		(
		SELECT 
			SEC_CDE
			,SEC_NAME 
		FROM 
			${NSOVIEW}.CSDC_INTG_SEC_INFO
		WHERE 
			SUBSTR(SEC_CTG,1,1)='3' AND MKT_SORT='0'
			AND S_DATE <= '${TXDATE}' AND E_DATE > '${TXDATE}'
		)T2
		
		ON 
			T1.SEC_CDE=T2.SEC_CDE
	WHERE 
		T1.HOLD_TYPE='ZYQ' --质押券
		AND T1.PRCS_DATE='${TXDATE}' 
	GROUP BY 1,2
	) A1
	
	LEFT JOIN
	
	(
	SELECT 
		SEC_CDE
		,CRENT_RATE
	FROM 
		${NSOVIEW}.CSDC_H_BPR_STD_STK_RT
	WHERE 
		S_DATE<='${TXDATE}' AND E_DATE>'${TXDATE}'
	)A2
	
	ON 
		A1.SEC_CDE=A2.SEC_CDE
GROUP BY 1,2,3

UNION ALL


--深市
SELECT
	'${TXDATE}' AS STAT_DATE
	,SUBSTR(CAST(1000000+A1.SEC_CDE AS CHAR(7)),2) AS SEC_CDE
	,A1.SEC_NAME
	,SUM(A1.PLG_VOL)/1E8 AS BOND_PAR_VAL
	,SUM(A1.PLG_VOL*A2.CNVT_RATE)/1E8 AS STD_STK_AMT
FROM
	(
	SELECT 
		T1.SEC_CDE
		,T2.SEC_NAME
		,SUM(PLG_VOL) AS PLG_VOL
	FROM 
		${NSOVIEW}.CSDC_S_BOND_PLG_HIS T1
		
		INNER JOIN
		
		(
		SELECT 
			SEC_CDE
			,SEC_NAME 
		FROM 
			${NSOVIEW}.CSDC_INTG_SEC_INFO
		WHERE 
			SUBSTR(SEC_CTG,1,1)='3' AND MKT_SORT='1' 
			AND S_DATE <= '${TXDATE}' AND E_DATE > '${TXDATE}'

		UNION ALL 

		SELECT 
			SEC_CDE
			,SEC_NAME 
		FROM 
			${NSOVIEW}.CSDC_INTG_SEC_INFO
		WHERE 
			SEC_CTG='90' AND MKT_SORT='1' 
			AND S_DATE <= '${TXDATE}' AND E_DATE > '${TXDATE}'
			AND (SUBSTR(SEC_CDE, 0, 5) = '1189' OR SEC_NAME LIKE '%国开%')

		)T2
		ON 
			T1.SEC_CDE=T2.SEC_CDE
	WHERE 
		S_DATE<='${TXDATE}' AND E_DATE>'${TXDATE}'
	GROUP BY 1,2
	)A1
	
	LEFT JOIN
	
	(
	SELECT 
		SEC_CDE
		,CNVT_RATE
	FROM 
		${NSOVIEW}.CSDC_S_SEC_CNVTR_HIS
	WHERE 
		S_DATE<='${TXDATE}' AND E_DATE>'${TXDATE}'
		AND APPLY_DATE='${TXDATE}'

	)A2
	
	ON 
		A1.SEC_CDE=A2.SEC_CDE
GROUP BY 1,2,3 
;

.IF ERRORCODE <> 0 THEN .QUIT 12;

.quit
