CREATE MULTISET TABLE NSSMSMART.SMS_QRY_2_STK_CLCT_FUN_RPT (
	STAT_DATE TITLE '统计日期' NOT NULL DATE FORMAT 'YYYYMMDD',
	SEC_EXCH_CDE TITLE '证券交易所代码' NOT NULL CHAR(1) CASESPECIFIC,
	SEC_CDE TITLE '证券代码' NOT NULL CHAR(6) CASESPECIFIC,
	IPO_CLCT_FUN_AMT TITLE '首发筹资金额' DECIMAL(24,2),
	OPEN_FI_CLCT_FUND_AMT TITLE '公开增发筹资金额' DECIMAL(24,2),
	ORTN_FI_CLCT_FUND_AMT TITLE '定向增发筹资金额' DECIMAL(24,2),
	RIGHT_CLCT_FUND_AMT TITLE '配股筹资金额' DECIMAL(24,2)
)
PRIMARY INDEX(STAT_DATE,SEC_EXCH_CDE,SEC_CDE) ;

 COMMENT ON  NSSMSMART.SMS_QRY_2_STK_CLCT_FUN_RPT is '股票筹资情况';

CREATE MULTISET TABLE NSSMSMART.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT (
	STAT_DATE TITLE '统计日期' NOT NULL DATE FORMAT 'YYYYMMDD',
	REPO_VART_SEC_CDE TITLE '回购品种证券代码' NOT NULL CHAR(6) CASESPECIFIC,
	REPO_TRAD_AMT TITLE '回购成交金额' DECIMAL(24,2),
	REPO_N_MAT_BAL TITLE '回购未到期余额' DECIMAL(24,2),
	STD_STK_AMT TITLE '标准券金额' DECIMAL(24,2),
	BOND_PAR_VAL TITLE '债券面值' DECIMAL(24,2)
)
PRIMARY INDEX(STAT_DATE,REPO_VART_SEC_CDE) ;

 COMMENT ON  NSSMSMART.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT is '交易所债券质押式回购交易情况';

CREATE MULTISET TABLE NSSMSMART.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT (
	STAT_DATE TITLE '统计日期' NOT NULL DATE FORMAT 'YYYYMMDD',
	SEC_CDE TITLE '证券代码' NOT NULL CHAR(6) CASESPECIFIC,
	SEC_NAME TITLE '证券名称' NOT NULL VARCHAR(50) CASESPECIFIC,
	BOND_PAR_VAL TITLE '债券面值' NOT NULL DECIMAL(24,2),
	STD_STK_AMT TITLE '标准券金额' NOT NULL DECIMAL(24,2)
)
PRIMARY INDEX(STAT_DATE,SEC_CDE) ;

 COMMENT ON  NSSMSMART.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT is '质押库中债券面值和标准券金额';

CREATE MULTISET TABLE NSSMSMART.SMS_QRY_2_HKST_TRAD_RPT (
	STAT_DATE TITLE '统计日期' NOT NULL DATE FORMAT 'YYYYMMDD',
	SEC_EXCH_CDE TITLE '港股通类别' NOT NULL CHAR(1) CASESPECIFIC,
	INVST_CLSF TITLE '投资者分类' NOT NULL CHAR(3) CASESPECIFIC,
	BUY_AMT TITLE '买入金额' NOT NULL DECIMAL(24,2) ,
	SAL_AMT TITLE '卖出金额' NOT NULL DECIMAL(24,2) ,
	TRAD_NET_AMT TITLE '买卖净额' NOT NULL DECIMAL(24,2)
)
PRIMARY INDEX(STAT_DATE,SEC_EXCH_CDE,INVST_CLSF) ;

 COMMENT ON  NSSMSMART.SMS_QRY_2_HKST_TRAD_RPT is '港股通交易数据';

CREATE MULTISET TABLE NSSMSMART.SMS_QRY_2_PPDM_SC_RPT (
	STAT_DATE TITLE '统计月份' NOT NULL DATE FORMAT 'YYYYMMDD',
	PPDM_NAME TITLE '证券公司辖区名称' NOT NULL VARCHAR(30) CASESPECIFIC,
	IF_JV TITLE '是否合资' NOT NULL VARCHAR(8) CASESPECIFIC,
	IF_HAVE_CUST_AM_QLF TITLE '是否具有资产管理业务资格' NOT NULL VARCHAR(8) CASESPECIFIC,
	COMP_CNT TITLE '公司家数' NOT NULL DECIMAL(24,0),
	BRH_CNT TITLE '营业部家数' NOT NULL DECIMAL(24,0),
	GAIN_COMP_CNT TITLE '盈利公司家数' NOT NULL DECIMAL(24,0),
	LOSS_COMP_CNT TITLE '亏损公司家数' NOT NULL DECIMAL(24,0),
	RISK_OVER_THRE_COMP_CNT TITLE '“风险覆盖率”超过预警标准公司家数' NOT NULL DECIMAL(24,0),
	RISK_OVER_REGU_COMP_CNT TITLE '“风险覆盖率”超过监管标准公司家数' NOT NULL DECIMAL(24,0),
	LEVE_OVER_THRE_COMP_CNT TITLE '“资本杠杆率”超过预警标准公司家数' NOT NULL DECIMAL(24,0),
	LEVL_OVER_REGU_COMP_CNT TITLE '“资本杠杆率”超过监管标准公司家数' NOT NULL DECIMAL(24,0),
	LIQU_OVER_THRE_COMP_CNT TITLE '“流动性覆盖率”超过预警标准公司家数' NOT NULL DECIMAL(24,0),
	LIQU_OVER_REGU_COMP_CNT TITLE '“流动性覆盖率”超过监管标准公司家数' NOT NULL DECIMAL(24,0),
	STAB_OVER_THRE_COMP_CNT TITLE '“净稳定资金率”超过预警标准公司家数' NOT NULL DECIMAL(24,0),
	STAB_OVER_REGU_COMP_CNT TITLE '“净稳定资金率”超过监管标准公司家数' NOT NULL DECIMAL(24,0),
	END_TOT_ASET TITLE '期末总资产' NOT NULL DECIMAL(24,2),
	END_NET_ASET TITLE '期末净资产' NOT NULL DECIMAL(24,2),
	PRFT_TOT_AMT TITLE '利润总额_当月' NOT NULL DECIMAL(24,2),
	NET_PRFT TITLE '净利润_当月' NOT NULL DECIMAL(24,2),
	BIZ_ENING TITLE '营业收入_当月' NOT NULL DECIMAL(24,2),
	NET_CAPTL_TOT_AMT TITLE '净资本总额' NOT NULL DECIMAL(24,2),
	RISK_CAPTL_RSRV_AMT TITLE '风险资本准备总额' NOT NULL DECIMAL(24,2),
	INTR_NET_ENING TITLE '利息净收入_当月' NOT NULL DECIMAL(24,2),
	INVSMT_INCM TITLE '投资收益_当月' NOT NULL DECIMAL(24,2),
	AGENT_NET_ENING TITLE '证券经纪业务净收入_当月' NOT NULL DECIMAL(24,2),
	INVSMT_BANK_NET_ENING TITLE '投资银行业务净收入_当月' NOT NULL DECIMAL(24,2),
	INVSMT_CNSLT_NET_ENING TITLE '投资咨询业务净收入_当月' NOT NULL DECIMAL(24,2),
	ASET_MNGMNT_NET_ENING TITLE '资产管理业务净收入_当月' NOT NULL DECIMAL(24,2)
)
PRIMARY INDEX(STAT_DATE,PPDM_NAME) ;

 COMMENT ON  NSSMSMART.SMS_QRY_2_PPDM_SC_RPT is '分辖区证券公司数据';

CREATE MULTISET TABLE NSSMSMART.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT (
	STAT_DATE TITLE '统计日期' NOT NULL DATE FORMAT 'YYYYMMDD',
	VLD_OAP_CNT TITLE '有效一码通数量' NOT NULL DECIMAL(24,0),
	OPEN_OAP_CNT TITLE '新开一码通数量' NOT NULL DECIMAL(24,0),
	TRAD_OAP_CNT TITLE '参与A股交易的一码通数量' NOT NULL DECIMAL(24,0),
	HOLD_OAP_CNT TITLE '持仓A股的一码通数量' NOT NULL DECIMAL(24,0)
)
PRIMARY INDEX(VLD_OAP_CNT) ;

 COMMENT ON  NSSMSMART.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT is '有效、新开、参与、持有一码通';