--------------------------------STK_CLCT_FUN_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT(
 STAT_DATE
,SEC_EXCH_CDE
,SEC_CDE
,IPO_CLCT_FUN_AMT
,OPEN_FI_CLCT_FUND_AMT
,ORTN_FI_CLCT_FUND_AMT
,RIGHT_CLCT_FUND_AMT
) AS LOCKING NSSMSMART.SMS_QRY_2_STK_CLCT_FUN_RPT FOR ACCESS SELECT
 STAT_DATE (TITLE '统计日期')
,SEC_EXCH_CDE (TITLE '证券交易所代码')
,SEC_CDE (TITLE '证券代码')
,IPO_CLCT_FUN_AMT (TITLE '首发筹资金额')
,OPEN_FI_CLCT_FUND_AMT (TITLE '公开增发筹资金额')
,ORTN_FI_CLCT_FUND_AMT (TITLE '定向增发筹资金额')
,RIGHT_CLCT_FUND_AMT (TITLE '配股筹资金额')
FROM NSSMSMART.SMS_QRY_2_STK_CLCT_FUN_RPT;

COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT AS '股票筹资情况';

COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.STAT_DATE AS '统计日期';
COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.SEC_EXCH_CDE AS '证券交易所代码';
COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.SEC_CDE AS '证券代码';
COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.IPO_CLCT_FUN_AMT AS '首发筹资金额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.OPEN_FI_CLCT_FUND_AMT AS '公开增发筹资金额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.ORTN_FI_CLCT_FUND_AMT AS '定向增发筹资金额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_STK_CLCT_FUN_RPT.RIGHT_CLCT_FUND_AMT AS '配股筹资金额';


--------------------------------EXCH_BOND_PLG_REPO_TRAD_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT(
 STAT_DATE
,REPO_VART_SEC_CDE
,REPO_TRAD_AMT
,REPO_N_MAT_BAL
,STD_STK_AMT
,BOND_PAR_VAL
) AS LOCKING NSSMSMART.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT FOR ACCESS SELECT
 STAT_DATE (TITLE '统计日期')
,REPO_VART_SEC_CDE (TITLE '回购品种证券代码')
,REPO_TRAD_AMT (TITLE '回购成交金额')
,REPO_N_MAT_BAL (TITLE '回购未到期余额')
,STD_STK_AMT (TITLE '标准券金额')
,BOND_PAR_VAL (TITLE '债券面值')
FROM NSSMSMART.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT;

COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT AS '交易所债券质押式回购交易情况';

COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT.STAT_DATE AS '统计日期';
COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT.REPO_VART_SEC_CDE AS '回购品种证券代码';
COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT.REPO_TRAD_AMT AS '回购成交金额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT.REPO_N_MAT_BAL AS '回购未到期余额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT.STD_STK_AMT AS '标准券金额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_EXCH_BOND_PLG_REPO_TRAD_RPT.BOND_PAR_VAL AS '债券面值';


--------------------------------BOND_PAR_VAL_STD_STK_AMT_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT(
 STAT_DATE
,SEC_CDE
,SEC_NAME
,BOND_PAR_VAL
,STD_STK_AMT
) AS LOCKING NSSMSMART.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT FOR ACCESS SELECT
 STAT_DATE (TITLE '统计日期')
,SEC_CDE (TITLE '证券代码')
,SEC_NAME (TITLE '证券名称')
,BOND_PAR_VAL (TITLE '债券面值')
,STD_STK_AMT (TITLE '标准券金额')
FROM NSSMSMART.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT;

COMMENT ON NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT AS '质押库中债券面值和标准券金额';

COMMENT ON NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT.STAT_DATE AS '统计日期';
COMMENT ON NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT.SEC_CDE AS '证券代码';
COMMENT ON NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT.SEC_NAME AS '证券名称';
COMMENT ON NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT.BOND_PAR_VAL AS '债券面值';
COMMENT ON NSSMSVIEW.SMS_QRY_2_BOND_PAR_VAL_STD_STK_AMT_RPT.STD_STK_AMT AS '标准券金额';


--------------------------------PPDM_SC_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT(
 STAT_DATE
,PPDM_NAME
,IF_JV
,IF_HAVE_CUST_AM_QLF
,COMP_CNT
,BRH_CNT
,GAIN_COMP_CNT
,LOSS_COMP_CNT
,RISK_OVER_THRE_COMP_CNT
,RISK_OVER_REGU_COMP_CNT
,LEVE_OVER_THRE_COMP_CNT
,LEVL_OVER_REGU_COMP_CNT
,LIQU_OVER_THRE_COMP_CNT
,LIQU_OVER_REGU_COMP_CNT
,STAB_OVER_THRE_COMP_CNT
,STAB_OVER_REGU_COMP_CNT
,END_TOT_ASET
,END_NET_ASET
,PRFT_TOT_AMT
,NET_PRFT
,BIZ_ENING
,NET_CAPTL_TOT_AMT
,RISK_CAPTL_RSRV_AMT
,INTR_NET_ENING
,INVSMT_INCM
,AGENT_NET_ENING
,INVSMT_BANK_NET_ENING
,INVSMT_CNSLT_NET_ENING
,ASET_MNGMNT_NET_ENING
) AS LOCKING NSSMSMART.SMS_QRY_2_PPDM_SC_RPT FOR ACCESS SELECT
 STAT_DATE (TITLE '统计月份')
,PPDM_NAME (TITLE '证券公司辖区名称')
,IF_JV (TITLE '是否合资')
,IF_HAVE_CUST_AM_QLF (TITLE '是否具有资产管理业务资格')
,COMP_CNT (TITLE '公司家数')
,BRH_CNT (TITLE '营业部家数')
,GAIN_COMP_CNT (TITLE '盈利公司家数')
,LOSS_COMP_CNT (TITLE '亏损公司家数')
,RISK_OVER_THRE_COMP_CNT (TITLE '"风险覆盖率"超过预警标准公司家数')
,RISK_OVER_REGU_COMP_CNT (TITLE '"风险覆盖率"超过监管标准公司家数')
,LEVE_OVER_THRE_COMP_CNT (TITLE '"资本杠杆率"超过预警标准公司家数')
,LEVL_OVER_REGU_COMP_CNT (TITLE '"资本杠杆率"超过监管标准公司家数')
,LIQU_OVER_THRE_COMP_CNT (TITLE '"流动性覆盖率"超过预警标准公司家数')
,LIQU_OVER_REGU_COMP_CNT (TITLE '"流动性覆盖率"超过监管标准公司家数')
,STAB_OVER_THRE_COMP_CNT (TITLE '"净稳定资金率"超过预警标准公司家数')
,STAB_OVER_REGU_COMP_CNT (TITLE '"净稳定资金率"超过监管标准公司家数')
,END_TOT_ASET (TITLE '期末总资产')
,END_NET_ASET (TITLE '期末净资产')
,PRFT_TOT_AMT (TITLE '利润总额_当月')
,NET_PRFT (TITLE '净利润_当月')
,BIZ_ENING (TITLE '营业收入_当月')
,NET_CAPTL_TOT_AMT (TITLE '净资本总额')
,RISK_CAPTL_RSRV_AMT (TITLE '风险资本准备总额')
,INTR_NET_ENING (TITLE '利息净收入_当月')
,INVSMT_INCM (TITLE '投资收益_当月')
,AGENT_NET_ENING (TITLE '证券经纪业务净收入_当月')
,INVSMT_BANK_NET_ENING (TITLE '投资银行业务净收入_当月')
,INVSMT_CNSLT_NET_ENING (TITLE '投资咨询业务净收入_当月')
,ASET_MNGMNT_NET_ENING (TITLE '资产管理业务净收入_当月')
FROM NSSMSMART.SMS_QRY_2_PPDM_SC_RPT;

COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT AS '分辖区证券公司数据';

COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.STAT_DATE AS '统计月份';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.PPDM_NAME AS '证券公司辖区名称';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.IF_JV AS '是否合资';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.IF_HAVE_CUST_AM_QLF AS '是否具有资产管理业务资格';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.COMP_CNT AS '公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.BRH_CNT AS '营业部家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.GAIN_COMP_CNT AS '盈利公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.LOSS_COMP_CNT AS '亏损公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.RISK_OVER_THRE_COMP_CNT AS '"风险覆盖率"超过预警标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.RISK_OVER_REGU_COMP_CNT AS '"风险覆盖率"超过监管标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.LEVE_OVER_THRE_COMP_CNT AS '"资本杠杆率"超过预警标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.LEVL_OVER_REGU_COMP_CNT AS '"资本杠杆率"超过监管标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.LIQU_OVER_THRE_COMP_CNT AS '"流动性覆盖率"超过预警标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.LIQU_OVER_REGU_COMP_CNT AS '"流动性覆盖率"超过监管标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.STAB_OVER_THRE_COMP_CNT AS '"净稳定资金率"超过预警标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.STAB_OVER_REGU_COMP_CNT AS '"净稳定资金率"超过监管标准公司家数';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.END_TOT_ASET AS '期末总资产';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.END_NET_ASET AS '期末净资产';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.PRFT_TOT_AMT AS '利润总额_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.NET_PRFT AS '净利润_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.BIZ_ENING AS '营业收入_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.NET_CAPTL_TOT_AMT AS '净资本总额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.RISK_CAPTL_RSRV_AMT AS '风险资本准备总额';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.INTR_NET_ENING AS '利息净收入_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.INVSMT_INCM AS '投资收益_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.AGENT_NET_ENING AS '证券经纪业务净收入_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.INVSMT_BANK_NET_ENING AS '投资银行业务净收入_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.INVSMT_CNSLT_NET_ENING AS '投资咨询业务净收入_当月';
COMMENT ON NSSMSVIEW.SMS_QRY_2_PPDM_SC_RPT.ASET_MNGMNT_NET_ENING AS '资产管理业务净收入_当月';


--------------------------------VLD_OPEN_TRAD_HOLD_OAP_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT(
 STAT_DATE
,VLD_OAP_CNT
,OPEN_OAP_CNT
,TRAD_OAP_CNT
,HOLD_OAP_CNT
) AS LOCKING NSSMSMART.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT FOR ACCESS SELECT
 STAT_DATE (TITLE '统计日期')
,VLD_OAP_CNT (TITLE '有效一码通数量')
,OPEN_OAP_CNT (TITLE '新开一码通数量')
,TRAD_OAP_CNT (TITLE '参与A股交易的一码通数量')
,HOLD_OAP_CNT (TITLE '持仓A股的一码通数量')
FROM NSSMSMART.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT;

COMMENT ON NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT AS '有效、新开、参与、持有一码通';

COMMENT ON NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT.STAT_DATE AS '统计日期';
COMMENT ON NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT.VLD_OAP_CNT AS '有效一码通数量';
COMMENT ON NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT.OPEN_OAP_CNT AS '新开一码通数量';
COMMENT ON NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT.TRAD_OAP_CNT AS '参与A股交易的一码通数量';
COMMENT ON NSSMSVIEW.SMS_QRY_2_VLD_OPEN_TRAD_HOLD_OAP_RPT.HOLD_OAP_CNT AS '持仓A股的一码通数量';


--------------------------------SMS_QRY_2_FIN_SEC_LN_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT(
		STAT_DATE
		,GAGE_BUY_AMT
		,GAGE_SAL_AMT
		,FIN_BUY_AMT
		,SLCPS_PAYBK_AMT
		,DRT_PAYBK_AMT
		,FIN_LQD_AMT
		,SEC_LN_SAL_AMT
		,BUY_STK_AS_VCR_AMT
		,AS_VCR_TRNSF_AMT
		,RM_SEC_TRNSF_AMT
		,SEC_LN_LQD_AMT
		,FIN_BAL
		,SEC_LN_BAL
		,MKT_AVG_GUART_RATE
) AS
SELECT	CAST(COALESCE(A.DATA_DATE,B.STAT_DATE) AS DATE FORMAT 'YYYYMMDD') AS STAT_DATE
		,A.GAGE_BUY_AMT
		,A.GAGE_SAL_AMT
		,A.FIN_BUY_AMT
		,A.SLCPS_PAYBK_AMT
		,A.DRT_PAYBK_AMT
		,A.FIN_LQD_AMT
		,A.SEC_LN_SAL_AMT
		,A.BUY_STK_AS_VCR_AMT
		,A.AS_VCR_TRNSF_AMT
		,A.RM_SEC_TRNSF_AMT
		,A.SEC_LN_LQD_AMT
		,B.FIN_BAL
		,B.SEC_LN_BAL
		,B.MKT_AVG_GUART_RATE
FROM
(SELECT	DATA_DATE
		,SUM(GAGE_BUY_AMT) AS GAGE_BUY_AMT
		,SUM(GAGE_SAL_AMT) AS GAGE_SAL_AMT
		,SUM(FIN_BUY_AMT) AS FIN_BUY_AMT
		,SUM(SLCPS_PAYBK_AMT) AS SLCPS_PAYBK_AMT
		,SUM(DRCT_PAYBK_AMT) AS DRT_PAYBK_AMT
		,SUM(FIN_LQD_AMT) AS FIN_LQD_AMT
		,SUM(SEC_LN_SAL_AMT) AS SEC_LN_SAL_AMT
		,SUM(BUY_STK_AS_VCR_AMT) AS BUY_STK_AS_VCR_AMT
		,SUM(AS_VCR_TRANS_AMT) AS AS_VCR_TRNSF_AMT
		,SUM(RM_SEC_TRANS_AMT) AS RM_SEC_TRNSF_AMT
		,SUM(SEC_LN_LQD_AMT) AS SEC_LN_LQD_AMT
FROM NSOVIEW.CSF_SC_CUST_TRAD_SUM
GROUP BY 1) A
FULL JOIN
(SELECT	STAT_DATE
		,SUM(CASE WHEN IDX_CDE = 'SK103' THEN IDX_VAL ELSE 0 END) AS FIN_BAL
		,SUM(CASE WHEN IDX_CDE = 'SK104' THEN IDX_VAL ELSE 0 END) AS SEC_LN_BAL
		,SUM(CASE WHEN IDX_CDE = 'SK106' THEN IDX_VAL ELSE 0 END) AS MKT_AVG_GUART_RATE
FROM NSPUBVIEW.KPI_SMKT_FS_AVG_MNTNC_GUT_IDX
WHERE FREQ = 'D'
AND IDX_CDE IN ('SK103','SK104','SK106')
GROUP BY 1
) B
ON A.DATA_DATE = B.STAT_DATE;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT IS '融资融券数据';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.GAGE_BUY_AMT IS '担保品买入金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.GAGE_SAL_AMT IS '担保品卖出金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.FIN_BUY_AMT IS '融资买入金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.SLCPS_PAYBK_AMT IS '卖券还款金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.DRT_PAYBK_AMT IS '直接还款金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.FIN_LQD_AMT IS '融资平仓金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.SEC_LN_SAL_AMT IS '融券卖出金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.BUY_STK_AS_VCR_AMT IS '买券还券金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.AS_VCR_TRNSF_AMT IS '还券划转金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.RM_SEC_TRNSF_AMT IS '余券划转金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.SEC_LN_LQD_AMT IS '融券平仓金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.FIN_BAL IS '融资余额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.SEC_LN_BAL IS '融券余额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_FIN_SEC_LN_RPT.MKT_AVG_GUART_RATE IS '市场平均担保比例';


--------------------------------SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT(
	STAT_DATE
	,SEC_EXCH_CDE
	,STK_INVST_SORT_CLSF_1
	,STK_INVST_SORT_CLSF_2
	,STK_INVST_SORT_CLSF_3
	,BNK_ID
	,SEC_SORT
	,BUY_AMT
	,SAL_AMT
	,BUY_VOL
	,SAL_VOL
	,TRAD_NET_AMT
	,PSTN_VOL
	,PSTN_MKT_VAL_ORIG_CRNC
) AS
SELECT	T1.STAT_DATE
		,T1.SEC_EXCH_CDE
		,T2.CLSF_1 AS STK_INVST_SORT_CLSF_1
		,T2.CLSF_2 AS STK_INVST_SORT_CLSF_2
		,T1.STK_INVST_SORT AS STK_INVST_SORT_CLSF_3
		,T1.BNK_ID
		,CASE
		WHEN T1.SEC_SORT = '31' THEN '301' --记账式企债
		WHEN T1.SEC_SORT = '32' THEN '305' --分离式可转债
		WHEN T1.SEC_SORT = '33' THEN '307' --公司债
		WHEN T1.SEC_SORT = '34' THEN '308' --资产证券
		WHEN T1.SEC_SORT = '35' THEN '309' --券商定向债券
		WHEN T1.SEC_SORT = '36' THEN '306' --可转换债券
		WHEN T1.SEC_SORT = '37' THEN '302' --记账式国债
		WHEN T1.SEC_SORT = '38' THEN '303' --凭证式国债
		WHEN T1.SEC_SORT = '39' THEN '310' --地方政府债
		WHEN T1.SEC_SORT = '3A' THEN '304' --凭证式企债
		WHEN T1.SEC_SORT = '3B' THEN '311' --中小企业私募债
		WHEN T1.SEC_SORT = '3C' THEN '312' --政策性金融债
		ELSE '999'
		END AS SEC_SORT
		,T1.BUY_AMT
		,T1.SAL_AMT
		,T1.BUY_VOL
		,T1.SAL_VOL
		,T1.TRAD_NET_AMT
		,T1.PSTN_VOL
		,T1.PSTN_MKT_VAL_ORIG_CRNC
FROM
(	SELECT	CAST(COALESCE(AA.STAT_DATE,BB.STAT_DATE) AS DATE FORMAT 'YYYYMMDD') AS STAT_DATE
			,COALESCE(AA.SEC_EXCH_CDE,BB.SEC_EXCH_CDE) AS SEC_EXCH_CDE
			,COALESCE(AA.STK_INVST_SORT,BB.STK_INVST_SORT) AS STK_INVST_SORT
			,COALESCE(AA.BNK_ID,BB.BNK_ID) AS BNK_ID
			,COALESCE(AA.SEC_SORT,BB.SEC_SORT) AS SEC_SORT
			,AA.BUY_VOL
			,AA.BUY_AMT
			,AA.SAL_VOL
			,AA.SAL_AMT
			,AA.TRAD_NET_AMT
			,BB.PSTN_VOL
			,BB.PSTN_MKT_VAL_ORIG_CRNC
	FROM
	(SELECT	A.STAT_DATE
			,A.SEC_EXCH_CDE
			,A.STK_INVST_SORT
			,A.BNK_ID
			,B.SEC_CTG AS SEC_SORT
			,SUM(A.BUY_VOL) AS BUY_VOL
			,SUM(A.BUY_AMT) AS BUY_AMT
			,SUM(A.SAL_VOL) AS SAL_VOL
			,SUM(A.SAL_AMT) AS SAL_AMT
			,SUM(A.BUY_AMT - A.SAL_AMT) AS TRAD_NET_AMT
	FROM NSPUBVIEW.MID_INVST_SEC_TRAD A
	INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
	ON A.STAT_DATE <= B.S_DATE
	AND A.STAT_DATE > B.S_DATE
	AND A.SEC_CDE = B.SEC_CDE
	AND A.SEC_EXCH_CDE = B.MKT_SORT
	AND B.SEC_CTG LIKE '3%'
	GROUP BY 1,2,3,4,5
	) AA
	FULL JOIN
	(SELECT	A.STAT_DATE
				,A.SEC_EXCH_CDE
				,A.STK_INVST_SORT
				,A.BNK_ID
				,B.SEC_CTG AS SEC_SORT
				,SUM(A.PSTN_VOL) AS PSTN_VOL
				,SUM(A.PSTN_MKT_VAL_ORIG_CRNC) AS PSTN_MKT_VAL_ORIG_CRNC
		FROM NSPUBVIEW.MID_INVST_SEC_PSTN A
		INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
		ON A.STAT_DATE <= B.S_DATE
		AND A.STAT_DATE > B.S_DATE
		AND A.SEC_CDE = B.SEC_CDE
		AND A.SEC_EXCH_CDE = B.MKT_SORT
		AND B.SEC_CTG LIKE '3%'
		GROUP BY 1,2,3,4,5
	) BB
	ON AA.STAT_DATE = BB.STAT_DATE
	AND AA.SEC_EXCH_CDE = BB.SEC_EXCH_CDE
	AND AA.STK_INVST_SORT = BB.STK_INVST_SORT
	AND AA.BNK_ID= BB.BNK_ID
	AND AA.SEC_SORT = BB.SEC_SORT
) T1
LEFT JOIN
(SELECT	CLSF_1
		,CLSF_2
		,CLSF_3
FROM NSPUBVIEW.CDE_STK_INVST_SORT
GROUP BY 1,2,3
) T2
ON T1.STK_INVST_SORT = T2.CLSF_3
;


COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT IS '分投资者类型债券交易持仓情况';

COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.SEC_EXCH_CDE IS '证券交易所代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.STK_INVST_SORT_CLSF_1 IS '股票投资者类别（一级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.STK_INVST_SORT_CLSF_2 IS '股票投资者类别（二级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.STK_INVST_SORT_CLSF_3 IS '股票投资者类别（三级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.BNK_ID IS '银行标识';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.SEC_SORT IS '证券类别';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.BUY_AMT IS '买入金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.SAL_AMT IS '卖出金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.BUY_VOL IS '买入数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.SAL_VOL IS '卖出数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.TRAD_NET_AMT IS '买卖净额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.PSTN_VOL IS '持仓数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_BOND_TRAD_PSTN_RPT.PSTN_MKT_VAL_ORIG_CRNC IS '持仓市值_原币';


--------------------------------SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT--------------------------------


/*
若同一上市公司含A股、B股，则将2只股票各个数据合并到A股
*/

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT(
		BIZ_DATE
		,COMP_ID
		,SEC_CDE
		,SEC_NAME
		,TCAP
		,TOT_MKT_VAL
		,LSTN_NEGT_CAP
		,LSTN_NEGT_MKT_VAL
		,SEC_EXCH_CDE
		,HDGS_CLSF_CDE
		,HDGS_CLSF_NAME
		,IDSTR_CTGR_CDE
		,IDSTR_CTGR_NAME
		,IDSTR_CLASS_CDE
		,IDSTR_CLASS_NAME
		,PPDM_CDE
		,PPDM_NAME
		,LSTN_BORD
) AS
SELECT	A.BIZ_DATE
		,A.COMP_ID
		,A.SEC_CDE
		,A.SEC_NAME
		,A.TCAP_EXCH
		,A.TOT_MKT_VAL_EXCH
		,A.LSTN_NEGT_CAP_EXCH
		,A.LSTN_NEGT_MKT_VAL_EXCH
		,B.SEC_EXCH_CDE
		,CASE	WHEN C.HDGS_TYPE LIKE '%中央国有%'   THEN '1'
				WHEN C.HDGS_TYPE LIKE '%地方国有%'   THEN '2'
				WHEN C.HDGS_TYPE LIKE '%社团集体%'   THEN '3'
				WHEN C.HDGS_TYPE LIKE '%自然人%'     THEN '4'
				WHEN C.HDGS_TYPE LIKE '%外商%'       THEN '5'
				WHEN C.HDGS_TYPE LIKE '%其他%'       THEN '6'
		END AS HDGS_CLSF_CDE
		,C.HDGS_TYPE AS HDGS_CLSF_NAME
		,B.IDSTR_CTGR_CDE
		,B.IDSTR_CTGR_NAME
		,B.IDSTR_CLASS_CDE
		,B.IDSTR_CLASS_NAME
		,B.PPDM_CDE
		,B.PPDM_NAME
		,B.LSTN_BORD
FROM
(SELECT	CAST(COALESCE(A.BIZ_DATE,B.BIZ_DATE) AS DATE FORMAT 'YYYYMMDD') AS BIZ_DATE
		,COALESCE(A.COMP_ID,B.COMP_ID) AS COMP_ID
		,COALESCE(A.SEC_CDE,B.SEC_CDE) AS SEC_CDE
		,COALESCE(A.STK_NAME,B.STK_NAME) AS SEC_NAME
		,SUM(ZEROIFNULL(A.TCAP_EXCH) +ZEROIFNULL(B.TCAP_EXCH)) AS TCAP_EXCH
		,SUM(ZEROIFNULL(A.TOT_MKT_VAL_EXCH)+ZEROIFNULL(B.TOT_MKT_VAL_EXCH)) AS TOT_MKT_VAL_EXCH
		,SUM(ZEROIFNULL(A.LSTN_NEGT_CAP_EXCH) + ZEROIFNULL(B.LSTN_NEGT_CAP_EXCH)) AS LSTN_NEGT_CAP_EXCH
		,SUM(ZEROIFNULL(A.LSTN_NEGT_MKT_VAL_EXCH) +ZEROIFNULL(B.LSTN_NEGT_MKT_VAL_EXCH)) AS LSTN_NEGT_MKT_VAL_EXCH
FROM
	(SELECT	A.BIZ_DATE
			,B.COMP_ID
			,A.SEC_CDE
			,B.STK_NAME
			,B.SEC_CTG
			,SUM(A.TOT_MKT_VAL_EXCH) AS TOT_MKT_VAL_EXCH
			,SUM(A.TCAP_EXCH) AS TCAP_EXCH
			,SUM(A.LSTN_NEGT_CAP_EXCH) AS LSTN_NEGT_CAP_EXCH
			,SUM(A.LSTN_NEGT_MKT_VAL_EXCH) AS LSTN_NEGT_MKT_VAL_EXCH
	FROM NSPUBVIEW.MID_STK_INFO A
	INNER JOIN NSPVIEW.PRD_STK_BSC_INFO_HIS  B
	ON A.SEC_CDE = B.STK_CDE
	AND	A.BIZ_DATE >= B.S_DATE
	AND	A.BIZ_DATE < B.E_DATE
	AND B.SEC_CTG IN('110')
	GROUP BY 1,2,3,4,5) A
	FULL JOIN
	(SELECT	A.BIZ_DATE
			,B.COMP_ID
			,A.SEC_CDE
			,B.STK_NAME
			,B.SEC_CTG
			,SUM(A.TOT_MKT_VAL_EXCH) AS TOT_MKT_VAL_EXCH
			,SUM(A.TCAP_EXCH) AS TCAP_EXCH
			,SUM(A.LSTN_NEGT_CAP_EXCH) AS LSTN_NEGT_CAP_EXCH
			,SUM(A.LSTN_NEGT_MKT_VAL_EXCH) AS LSTN_NEGT_MKT_VAL_EXCH
	FROM NSPUBVIEW.MID_STK_INFO A
	INNER JOIN NSPVIEW.PRD_STK_BSC_INFO_HIS  B
	ON A.SEC_CDE = B.STK_CDE
	AND	A.BIZ_DATE >= B.S_DATE
	AND	A.BIZ_DATE < B.E_DATE
	AND B.SEC_CTG IN('120')
	GROUP BY 1,2,3,4,5) B
ON A.BIZ_DATE = B.BIZ_DATE
AND A.COMP_ID = B.COMP_ID
GROUP BY 1,2,3,4
) A
LEFT JOIN NSPVIEW.PRD_STK_BSC_INFO_HIS B
ON A.BIZ_DATE >=  B.S_DATE  
AND	A.BIZ_DATE < B.E_DATE
AND A.SEC_CDE = B.STK_CDE
AND B.SEC_CTG IN('110','120')
LEFT JOIN NSOVIEW.RCS_LC_HDGS_CNDT_CLSF C
ON A.SEC_CDE = C.SEC_CD
WHERE A.BIZ_DATE >= C.STAT_DATE
AND	C.NEWEST_FLAG = '1'
QUALIFY (ROW_NUMBER() OVER(PARTITION BY BIZ_DATE,SEC_CDE ORDER BY C.STAT_DATE DESC)) = 1;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT IS '上市公司股本市值明细表';

COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.BIZ_DATE IS '业务日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.COMP_ID IS '公司ID';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.SEC_CDE IS '证券代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.SEC_NAME IS '证券名称';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.TCAP IS '总股本';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.TOT_MKT_VAL IS '总市值';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.LSTN_NEGT_CAP IS '已上市流通股本';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.LSTN_NEGT_MKT_VAL IS '已上市流通市值';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.SEC_EXCH_CDE IS '证券交易所代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.HDGS_CLSF_CDE IS '控股分类代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.HDGS_CLSF_NAME IS '控股分类名称';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.IDSTR_CTGR_CDE IS '行业门类代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.IDSTR_CTGR_NAME IS '行业门类名称';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.IDSTR_CLASS_CDE IS '行业大类代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.IDSTR_CLASS_NAME IS '行业大类名称';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.PPDM_CDE IS '辖区代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.PPDM_NAME IS '辖区名称';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_LIST_COMP_CAP_MKT_VAL_DTL_RPT.LSTN_BORD IS '上市板块';



--------------------------------SMS_QRY_2_PPDM_FC_RPT--------------------------------

REPLACE VIEW NSSMSVIEW.SMS_QRY_2_PPDM_FC_RPT (
STAT_DATE
,PPDM_CDE
,PPDM_NAME
,COMP_CNT
,BRH_CNT
,EMPLY_CNT
,TOT_ASET
,NET_ASET
,BIZ_ENING
,BIZ_SUPT
,PRFT_TOT_AMT
,NET_PRFT
,NET_CAPTL_TOT_AMT
)
AS SELECT
STAT_DATE                                                 (TITLE '统计月份')
,PPDM_CDE                                                 (TITLE '辖区代码')
,PPDM_NAME                                                (TITLE '辖区名称')
,SUM(CASE WHEN IDX_CDE = 'PI014' THEN IDX_VAL ELSE 0 END) (TITLE '公司家数')            AS COMP_CNT
,SUM(CASE WHEN IDX_CDE = 'PI015' THEN IDX_VAL ELSE 0 END) (TITLE '营业部家数')          AS BRH_CNT
,SUM(CASE WHEN IDX_CDE = 'PI016' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司就业人员数')  AS EMPLY_CNT
,SUM(CASE WHEN IDX_CDE = 'PI017' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司总资产')      AS TOT_ASET
,SUM(CASE WHEN IDX_CDE = 'PI018' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司净资产')      AS NET_ASET
,SUM(CASE WHEN IDX_CDE = 'PI020' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司营业收入')    AS BIZ_ENING
,SUM(CASE WHEN IDX_CDE = 'PI021' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司营业支出')    AS BIZ_SUPT
,SUM(CASE WHEN IDX_CDE = 'PI022' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司利润总额')    AS PRFT_TOT_AMT
,SUM(CASE WHEN IDX_CDE = 'PI023' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司净利润')      AS NET_PRFT
,SUM(CASE WHEN IDX_CDE = 'PI024' THEN IDX_VAL ELSE 0 END) (TITLE '期货公司净资本总额')  AS NET_CAPTL_TOT_AMT
FROM NSPUBVIEW.KPI_FC_IDX A, NSPUBVIEW.CDE_PPDM_CDE B
WHERE
A.REG_JUR = B.PPDM_CDE
AND A.FREQ = 'M'
GROUP BY 1,2,3
;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_PPDM_FC_RPT IS '分辖区期货公司数据';


--------------------------------SMS_QRY_2_HKST_TRAD_RPT--------------------------------


REPLACE VIEW NSSMSVIEW.SMS_QRY_2_HKST_TRAD_RPT (
STAT_DATE
,SEC_EXCH_CDE
,INVST_CLSF
,BUY_AMT
,SAL_AMT
,TRAD_NET_AMT
)
AS SELECT
STAT_DATE
,SEC_EXCH_CDE
,CASE
 	 WHEN INVST_CLSF IN ('235') THEN '专业机构' -- '证券投资基金'
 	 WHEN INVST_CLSF IN ('231') THEN '专业机构' -- '证券公司自营'
 	 WHEN INVST_CLSF IN ('239') THEN '专业机构' -- 'QFII'
 	 WHEN INVST_CLSF IN ('233') THEN '专业机构' -- '信托公司'
 	 WHEN INVST_CLSF IN ('110') THEN '自然人'   -- '自然人'
 	 WHEN INVST_CLSF IN ('236') THEN '专业机构' -- '社保基金'
 	 WHEN INVST_CLSF IN ('234') THEN '专业机构' -- '保险公司'
 	 WHEN INVST_CLSF IN ('232') THEN '专业机构' -- '证券公司集合理财'
 	 WHEN INVST_CLSF IN ('238') THEN '专业机构' -- '企业年金'
     WHEN INVST_CLSF IN ('23A') THEN '专业机构' -- '基金专户理财'
 	 WHEN INVST_CLSF IN ('23C') THEN '专业机构' -- 'RQFII'
 	 ELSE '一般机构'
END AS INVST_CLSF
,SUM(BUY_AMT) AS BUY_AMT
,SUM(SAL_AMT) AS SAL_AMT
,SUM(TRAD_NET_AMT) AS TRAD_NET_AMT
FROM nsSMSMART.SMS_QRY_2_HKST_TRAD_RPT
GROUP BY 1,2,3
;


COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_HKST_TRAD_RPT IS '港股通交易数据';


--------------------------------SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT--------------------------------


REPLACE VIEW NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT(
		STAT_DATE
		,SEC_EXCH_CDE
		,SEC_CDE
		,SEC_SORT
		,PSTN_VOL
		,PSTN_MKT_VAL_ORIG_CRNC
		,BOND_PAR_VAL
) AS
SELECT	CAST(COALESCE(A.STAT_DATE,B.STAT_DATE) AS DATE FORMAT 'YYYYMMDD') AS STAT_DATE
		,COALESCE(A.SEC_EXCH_CDE,B.SEC_EXCH_CDE) AS SEC_EXCH_CDE
		,COALESCE(A.SEC_CDE,B.BOND_CDE) AS SEC_CDE
		,COALESCE(A.SEC_CLSF,'') AS SEC_SORT
		,A.PSTN_VOL
		,A.PSTN_MKT_VAL_ORIG_CRNC
		,B.BOND_PAR_VAL
FROM
(
	SELECT	STAT_DATE
			,SEC_CDE
			,SEC_EXCH_CDE
			,SEC_CLSF
			,SUM(PSTN_VOL) AS PSTN_VOL
			,SUM(PSTN_MKT_VAL_ORIG_CRNC) AS PSTN_MKT_VAL_ORIG_CRNC
	FROM NSPUBVIEW.MID_INVST_SEC_PSTN
	WHERE SEC_CLSF LIKE '3%'
	GROUP BY 1,2,3,4
) A
FULL JOIN
(
	SELECT	STAT_DATE
			,BOND_CDE
			,SEC_EXCH_CDE
			,BOND_PAR_VAL
	FROM NSPUBVIEW.MID_EXCH_BOND_INFO
	GROUP BY 1,2,3,4
) B
ON A.STAT_DATE = B.STAT_DATE
AND A.SEC_CDE= B.BOND_CDE
AND A.SEC_EXCH_CDE = B.SEC_EXCH_CDE
;


COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT IS '个券托管面值';

COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.SEC_EXCH_CDE IS '证券交易所代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.SEC_CDE IS '证券代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.SEC_SORT IS '证券类别';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.PSTN_VOL IS '持仓数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.PSTN_MKT_VAL_ORIG_CRNC IS '持仓市值_原币';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_CSTD_PAR_VAL_RPT.BOND_PAR_VAL IS '债券面值';


--------------------------------SMS_QRY_2_DOM_IDX_PB_RPT--------------------------------

REPLACE VIEW NSSMSView.SMS_QRY_2_DOM_IDX_PB_RPT (
 BIZ_DATE,
IDX_NAME_000300,
IDX_NAME_000001,
IDX_NAME_399106,
IDX_NAME_399001 ,
IDX_NAME_399005 ,
IDX_NAME_000016 ,
IDX_NAME_000010 ,
IDX_NAME_399006
 )
 AS  
 SELECT biz_date  
,SUM(CASE WHEN stat_angle_cde = '000300' THEN pb ELSE 0 end ) I_000300 
,SUM(CASE WHEN stat_angle_cde = '000001' THEN pb ELSE 0 end ) I_000001
,SUM(CASE WHEN stat_angle_cde = '399106' THEN pb ELSE 0 end ) I_399106 
,SUM(CASE WHEN stat_angle_cde = '399001' THEN pb ELSE 0 end ) I_399001 
,SUM(CASE WHEN stat_angle_cde = '399005' THEN pb ELSE 0 end ) I_399005 
,SUM(CASE WHEN stat_angle_cde = '000016' THEN pb ELSE 0 end ) I_000016 
,SUM(CASE WHEN stat_angle_cde = '000010' THEN pb ELSE 0 end ) I_000010 
,SUM(CASE WHEN stat_angle_cde = '399006' THEN pb ELSE 0 end ) I_399006

FROM nspubview.mid_pe_rate 
WHERE freq = 'd' AND STAT_ANGLE_CDE IN ('000300','000001','399106','399001','399005','000016','000010','399006')
AND BIZ_DATE BETWEEN CAST('20140304' AS DATE FORMAT 'YYYYMMDD') AND CAST('20140404' AS DATE FORMAT 'YYYYMMDD')
GROUP BY 1 ;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT IS '境内股票市净率';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.BIZ_DATE IS '业务日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_000300 IS '沪深300指数';  
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_000001 IS '上证综合指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_399106 IS '深证综合指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_399001 IS '深证成份指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_399005 IS '中小板指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_000016 IS '上证50指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_000010 IS '上证180指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_PB_RPT.IDX_NAME_399006 IS '创业板指数';


--------------------------------SMS_QRY_2_DOM_IDX_STC_PE_RPT--------------------------------


REPLACE VIEW NSSMSView.SMS_QRY_2_DOM_IDX_STC_PE_RPT (
BIZ_DATE,
IDX_NAME_000300,
IDX_NAME_000001,
IDX_NAME_399106,
IDX_NAME_399001 ,
IDX_NAME_399005 ,
IDX_NAME_000016 ,
IDX_NAME_000010 ,
IDX_NAME_399006
 )
 AS  
 SELECT biz_date  
,SUM(CASE WHEN stat_angle_cde = '000300' THEN STC_PE ELSE 0 end ) I_000300 
,SUM(CASE WHEN stat_angle_cde = '000001' THEN STC_PE ELSE 0 end ) I_000001
,SUM(CASE WHEN stat_angle_cde = '399106' THEN STC_PE ELSE 0 end ) I_399106 
,SUM(CASE WHEN stat_angle_cde = '399001' THEN STC_PE ELSE 0 end ) I_399001 
,SUM(CASE WHEN stat_angle_cde = '399005' THEN STC_PE ELSE 0 end ) I_399005 
,SUM(CASE WHEN stat_angle_cde = '000016' THEN STC_PE ELSE 0 end ) I_000016 
,SUM(CASE WHEN stat_angle_cde = '000010' THEN STC_PE ELSE 0 end ) I_000010 
,SUM(CASE WHEN stat_angle_cde = '399006' THEN STC_PE ELSE 0 end )I_399006

FROM nspubview.mid_pe_rate 
WHERE freq = 'd' AND STAT_ANGLE_CDE IN ('000300','000001','399106','399001','399005','000016','000010','399006')
AND BIZ_DATE BETWEEN CAST('20140304' AS DATE FORMAT 'YYYYMMDD') AND CAST('20140404' AS DATE FORMAT 'YYYYMMDD')
GROUP BY 1;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT IS '境内股票市净率';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.BIZ_DATE IS '业务日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_000300 IS '沪深300指数';  
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_000001 IS '上证综合指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_399106 IS '深证综合指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_399001 IS '深证成份指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_399005 IS '中小板指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_000016 IS '上证50指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_000010 IS '上证180指数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_DOM_IDX_STC_PE_RPT.IDX_NAME_399006 IS '创业板指数';


--------------------------------SMS_QRY_2_STK_TRAD_RPT--------------------------------

REPLACE VIEW NSSMSView.SMS_QRY_2_STK_TRAD_RPT (
  STAT_DATE,
  SEC_CDE,
  SEC_EXCH_CDE,
  SEC_SORT,
  CSI_300,
  LSTN_BORD,
  TRAD_VOL,
  TRAD_AMT,
  TRAD_CNT
  
)
 AS 
SELECT 
  A.STAT_DATE ( TITLE '统计日期'),
  A.SEC_CDE ( TITLE '证券代码'),
  CASE
  WHEN A.SEC_EXCH_CDE=0 THEN '上交所'
  WHEN A.SEC_EXCH_CDE=1 THEN '深交所'
  END AS SEC_EXCH_CDE ,
  CASE
  WHEN A.SEC_CLSF=110 THEN 'A股'
  WHEN A.SEC_CLSF=120 THEN 'B股'
  END AS SEC_SORT  ,
  CASE WHEN K.SEC_CDE IS NOT NULL THEN '是' ELSE '否' END AS CSI_300,
 C.SEC_MKT_LVL_SORT_NAME AS LSTN_BORD ,
  SUM(A.BUY_VOL) +SUM(A.SAL_VOL) AS TRAD_VOL  ,
  SUM(A.BUY_AMT)+SUM(A.SAL_AMT) AS TRAD_AMT,
  SUM(A.BUY_CNT)+SUM(A.SAL_CNT) AS TRAD_CNT
 from  nsPUBView.MID_INVST_SEC_TRAD A
 
LEFT JOIN nsOVIEW.CSDC_INTG_SEC_INFO B
ON  A.SEC_CDE=B.SEC_CDE
LEFT JOIN CMSSVIEW.CDE_SEC_MKT_LVL_SORT C                               --市场层次类别
ON  B.MKT_LVL_SORT=C.SEC_MKT_LVL_SORT_CDE
LEFT JOIN NSPVIEW.PRD_OBJ_STK_HIS K					--标的股历史表CSI_300
ON A.SEC_CDE = K.SEC_CDE
AND A.SEC_EXCH_CDE = K.SEC_EXCH_CDE
AND K.OBJ_TYPE = '007'
AND K.S_DATE <= A.STAT_DATE
AND K.E_DATE > A.STAT_DATE
GROUP BY 1,2,3,4,5,6;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT IS '个股交易情况';

COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.SEC_CDE   IS '证券代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.SEC_EXCH_CDE IS '证券交易所';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.SEC_SORT IS '证券分类';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.CSI_300 IS '板块类型';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.LSTN_BORD IS '证券是否沪深300成分股';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.TRAD_VOL IS '成交数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.TRAD_AMT IS '成交金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_STK_TRAD_RPT.TRAD_CNT IS '成交笔数';


--------------------------------SMS_QRY_2_BOND_TRAD_RPT--------------------------------

REPLACE VIEW NSSMSView.SMS_QRY_2_BOND_TRAD_RPT (
  STAT_DATE,
  SEC_CDE,
  SEC_EXCH_CDE,
  SEC_SORT,
  TRAD_VOL,
  TRAD_AMT,
  TRAD_AMT_MKT_PRC,
  TRAD_CNT,
  BUY_VOL ,
  BUY_AMT ,
  SAL_VOL ,
  SAL_AMT
   )
 AS 
SELECT 
  STAT_DATE,
  A.SEC_CDE,
  CASE
  WHEN SEC_EXCH_CDE=0 THEN '上交所'
  WHEN SEC_EXCH_CDE=1 THEN '深交所'
  END AS SEC_EXCH_CDE ,
  CASE
		WHEN B.SEC_CTG = '31' THEN '301' --记账式企债
		WHEN B.SEC_CTG = '32' THEN '305' --分离式可转债
		WHEN B.SEC_CTG = '33' THEN '307' --公司债
		WHEN B.SEC_CTG = '34' THEN '308' --资产证券
		WHEN B.SEC_CTG = '35' THEN '309' --券商定向债券
		WHEN B.SEC_CTG = '36' THEN '306' --可转换债券
		WHEN B.SEC_CTG = '37' THEN '302' --记账式国债
		WHEN B.SEC_CTG = '38' THEN '303' --凭证式国债
		WHEN B.SEC_CTG = '39' THEN '310' --地方政府债
		WHEN B.SEC_CTG = '3A' THEN '304' --凭证式企债
		WHEN B.SEC_CTG = '3B' THEN '311' --中小企业私募债
		WHEN B.SEC_CTG = '3C' THEN '312' --政策性金融债
		ELSE '999'
		END AS SEC_SORT ,
  SUM(BUY_VOL) +SUM(SAL_VOL)AS TRAD_VOL ,
  SUM(BUY_AMT)+SUM(SAL_AMT) AS TRAD_AMT,
  SUM(BUY_AMT_MKT_PRC)+SUM(SAL_AMT_MKT_PRC )AS TRAD_AMT_MKT_PRC, --成交金额市价
  SUM(BUY_CNT)+SUM(SAL_CNT) AS TRAD_CNT,
  SUM(BUY_VOL)AS BUY_VOL ,
  SUM(BUY_AMT)AS BUY_AMT,
  SUM(SAL_VOL)AS SAL_VOL,
  SUM(SAL_AMT)AS SAL_AMT
from  nsPUBView.MID_INVST_SEC_TRAD A
INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
		ON A.STAT_DATE <= B.S_DATE
		AND A.STAT_DATE > B.S_DATE
		AND A.SEC_CDE = B.SEC_CDE
		AND A.SEC_EXCH_CDE = B.MKT_SORT
		AND B.SEC_CTG LIKE '3%'
		GROUP BY 1,2,3,4;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT IS '个券交易情况';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.SEC_CDE   IS '证券代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.SEC_EXCH_CDE IS '证券交易所代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.SEC_SORT IS '证券分类';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.TRAD_VOL IS '成交数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.TRAD_AMT IS '成交金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.TRAD_AMT_MKT_PRC IS '成交金额_市价';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.TRAD_CNT IS '成交笔数';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.BUY_VOL IS '买入数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.BUY_AMT IS '买入金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.SAL_VOL IS '卖出数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_BOND_TRAD_RPT.SAL_AMT IS '卖出金额';


--------------------------------SMS_QRY_2_OPT_TRAD_PSTN_RPT_1--------------------------------

REPLACE VIEW NSSMSView.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1 (
	STAT_DATE,
	OPT_CNTR_PROD_CDE,
	SUBSC_VOL,
	PUT_VOL,
	SUBSC_AMT,
	PUT_AMT,
	END_SUBSC_PSTN_VOL,
	END_PUT_PSTN_VOL
)
 AS 
  SELECT 
	STAT_DATE  , --统计日期
	OPT_CNTR_PROD_CDE , --期权合约产品代码
	SUM(SUBSC_BUY_VOL) AS SUBSC_VOL ,
	SUM(PUT_BUY_VOL) AS PUT_VOL ,
	SUM(SUBSC_BUY_AMT) AS SUBSC_AMT ,
	SUM(PUT_BUY_AMT) AS PUT_AMT ,
	SUM(SUBSC_RIGHT_PSTN_QTT) AS END_SUBSC_PSTN_VOL ,
	SUM(PUT_RIGHT_PSTN_QTT) AS END_PUT_PSTN_VOL	
 from  nsPUBView.MID_INVST_STK_OPT_TRAD_PSTN
 GROUP BY 1,2;

COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1 IS '期权交易持仓数据1';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.OPT_CNTR_PROD_CDE IS '期权合约产品代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.SUBSC_VOL IS '认购数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.PUT_VOL IS '认沽数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.SUBSC_AMT IS '认购金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.PUT_AMT IS '认沽金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.END_SUBSC_PSTN_VOL IS '期末认购持仓数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_1.END_PUT_PSTN_VOL IS '期末认沽持仓数量';


--------------------------------SMS_QRY_2_OPT_TRAD_PSTN_RPT_2--------------------------------

REPLACE VIEW NSSMSView.SMS_QRY_2_OPT_TRAD_PSTN_RPT_2 (
	STAT_DATE,
	AMT_TYPE,
	AMT
)
 AS
SELECT B.CALENDAR_DATE AS STAT_DATE
       ,CASE a.amt_type
        WHEN '000' THEN '保证金余额'
        WHEN '002' THEN '占用保证金'
        ELSE ''
        END as amt_type
       ,SUM (a.amt)/100000000 AS AMT
FROM NSOVIEW.CSDC_INOVT_DD_CLSF_BAL a--ACT_衍生品保证金分类余额历史_沪_SRC
INNER JOIN NSPVIEW.PTY_TRAD_CLND B
ON A.S_DATE <= B.CALENDAR_DATE
AND A.E_DATE > B.CALENDAR_DATE
AND B.IF_TRADDAY = 1
GROUP BY 1,2;
COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_2 IS '期权交易持仓数据2';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_2.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_2.AMT_TYPE IS '金额类型';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_OPT_TRAD_PSTN_RPT_2.AMT IS '金额';


--------------------------------SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1--------------------------------

REPLACE VIEW nsSMSView.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1(
	STAT_DATE               --统计日期
	,SEC_EXCH_CDE           --证券交易所代码
	,STK_INVST_SORT_CLSF_1  --股票投资者类别（一级）
	,STK_INVST_SORT_CLSF_2  --股票投资者类别（二级）
	,STK_INVST_SORT_CLSF_3  --股票投资者类别（三级）
	,BNK_ID                --银行标识
	,CAP_TYPE              --股本类别
    ,SEC_SORT              --证券分类
    ,LSTN_BORD             --板块类型
    ,BUY_AMT               --买入金额
	,SAL_AMT               --卖出金额
	,TRAD_NET_AMT          --买卖净额
	,PSTN_VOL              --持仓数量
	,PSTN_MKT_VAL_ORIG_CRNC   --持仓市值_原币
) AS
SELECT	T1.STAT_DATE
		,T1.SEC_EXCH_CDE
		,T2.CLSF_1 AS STK_INVST_SORT_CLSF_1
		,T2.CLSF_2 AS STK_INVST_SORT_CLSF_2
		,T1.STK_INVST_SORT AS STK_INVST_SORT_CLSF_3
		,T1.BNK_ID
        ,CASE
		WHEN T1.CAP_TYPE = 0 THEN '非限售' --记账式企债
		WHEN T1.CAP_TYPE = 1 THEN '限售'   --分离式可转债
		END AS CAP_TYPE
		,CASE
		WHEN T1.SEC_SORT =  110 THEN 'A股' --记账式企债
		WHEN T1.SEC_SORT = 120  THEN 'B股' --分离式可转债
		END AS SEC_SORT
        ,T3.SEC_MKT_LVL_SORT_NAME AS LSTN_BORD   --板块类型
		,T1.BUY_AMT
		,T1.SAL_AMT
		,T1.TRAD_NET_AMT
		,T1.PSTN_VOL
		,T1.PSTN_MKT_VAL_ORIG_CRNC
FROM
(	SELECT	COALESCE(AA.STAT_DATE,BB.STAT_DATE) AS STAT_DATE
			,COALESCE(AA.SEC_EXCH_CDE,BB.SEC_EXCH_CDE) AS SEC_EXCH_CDE
			,COALESCE(AA.STK_INVST_SORT,BB.STK_INVST_SORT) AS STK_INVST_SORT
			,COALESCE(AA.BNK_ID,BB.BNK_ID) AS BNK_ID
			,COALESCE(AA.SEC_SORT,BB.SEC_SORT) AS SEC_SORT
            ,COALESCE(AA.MKT_LVL_SORT,BB.MKT_LVL_SORT) AS MKT_LVL_SORT
			,AA.BUY_VOL
			,AA.BUY_AMT
			,AA.SAL_VOL
			,AA.SAL_AMT
			,AA.TRAD_NET_AMT
            ,BB.CAP_TYPE         --股本类型
			,BB.PSTN_VOL
			,BB.PSTN_MKT_VAL_ORIG_CRNC
	FROM
	(SELECT	A.STAT_DATE
			,A.SEC_EXCH_CDE
			,A.STK_INVST_SORT
			,A.BNK_ID
			,A.SEC_CLSF AS SEC_SORT
            ,B.MKT_LVL_SORT
			,SUM(A.BUY_VOL) AS BUY_VOL
			,SUM(A.BUY_AMT) AS BUY_AMT
			,SUM(A.SAL_VOL) AS SAL_VOL
			,SUM(A.SAL_AMT) AS SAL_AMT
			,SUM(A.BUY_AMT - A.SAL_AMT) AS TRAD_NET_AMT
	FROM NSPUBVIEW.MID_INVST_SEC_TRAD A
	INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
	ON A.STAT_DATE <= B.S_DATE
	AND A.STAT_DATE > B.S_DATE
	AND A.SEC_CDE = B.SEC_CDE
	AND A.SEC_EXCH_CDE = B.MKT_SORT
	AND B.SEC_CTG IN ('11','12')
	GROUP BY 1,2,3,4,5,6
	) AA
	FULL JOIN
	(SELECT	A.STAT_DATE
				,A.SEC_EXCH_CDE
				,A.STK_INVST_SORT
				,A.BNK_ID
				,A.SEC_CLSF AS SEC_SORT
                ,A.CAP_TYPE AS CAP_TYPE
                ,B.MKT_LVL_SORT
				,SUM(A.PSTN_VOL) AS PSTN_VOL
				,SUM(A.PSTN_MKT_VAL_ORIG_CRNC) AS PSTN_MKT_VAL_ORIG_CRNC
		FROM NSPUBVIEW.MID_INVST_SEC_PSTN A
		INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
		ON A.STAT_DATE <= B.S_DATE
		AND A.STAT_DATE > B.S_DATE
		AND A.SEC_CDE = B.SEC_CDE
		AND A.SEC_EXCH_CDE = B.MKT_SORT
		AND B.SEC_CTG IN ('11','12')
		GROUP BY 1,2,3,4,5,6,7
	) BB
	ON AA.STAT_DATE = BB.STAT_DATE
	AND AA.SEC_EXCH_CDE = BB.SEC_EXCH_CDE
	AND AA.STK_INVST_SORT = BB.STK_INVST_SORT
	AND AA.BNK_ID= BB.BNK_ID
	AND AA.SEC_SORT = BB.SEC_SORT
) T1
LEFT JOIN
(SELECT	CLSF_1
		,CLSF_2
		,CLSF_3
FROM NSPUBVIEW.CDE_STK_INVST_SORT
GROUP BY 1,2,3
) T2
ON T1.STK_INVST_SORT = T2.CLSF_3
LEFT JOIN CMSSVIEW.CDE_SEC_MKT_LVL_SORT T3                              --市场层次类别
ON  T1.MKT_LVL_SORT=T3.SEC_MKT_LVL_SORT_CDE
;


COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1 IS '分投资者类型股票交易持仓情况1';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.SEC_EXCH_CDE IS '证券交易所代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.STK_INVST_SORT_CLSF_1 IS '股票投资者类别（一级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.STK_INVST_SORT_CLSF_2 IS '股票投资者类别（二级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.STK_INVST_SORT_CLSF_3 IS '股票投资者类别（三级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.BNK_ID IS '银行标识';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.CAP_TYPE IS '股本类别';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.SEC_SORT IS '证券分类';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.LSTN_BORD  IS '板块类型';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.BUY_AMT  IS '买入金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.SAL_AMT IS '卖出金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.TRAD_NET_AMT IS '买卖净额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.PSTN_VOL IS '持仓数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_1.PSTN_MKT_VAL_ORIG_CRNC IS '持仓市值_原币';



--------------------------------SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2--------------------------------


REPLACE VIEW nsSMSView.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2(
	STAT_DATE               --统计日期
    ,SEC_CDE                --证券代码
	,SEC_EXCH_CDE           --证券交易所代码
	,STK_INVST_SORT_CLSF_1  --股票投资者类别（一级）
	,STK_INVST_SORT_CLSF_2  --股票投资者类别（二级）
	,STK_INVST_SORT_CLSF_3  --股票投资者类别（三级）
	,BNK_ID                --银行标识
	,CAP_TYPE              --股本类别
    ,SEC_SORT              --证券分类
    ,LSTN_BORD             --板块类型
    ,CSI_300               --证券是否是沪深300成分股
    ,BUY_AMT               --买入金额
	,SAL_AMT               --卖出金额
	,TRAD_NET_AMT          --买卖净额
	,PSTN_VOL              --持仓数量
	,PSTN_MKT_VAL_ORIG_CRNC   --持仓市值_原币
) AS
SELECT	T1.STAT_DATE
                ,T1.SEC_CDE
		,T1.SEC_EXCH_CDE
		,T2.CLSF_1 AS STK_INVST_SORT_CLSF_1
		,T2.CLSF_2 AS STK_INVST_SORT_CLSF_2
		,T1.STK_INVST_SORT AS STK_INVST_SORT_CLSF_3
		,T1.BNK_ID
        ,CASE
		WHEN T1.CAP_TYPE = 0 THEN '非限售' --记账式企债
		WHEN T1.CAP_TYPE = 1 THEN '限售'   --分离式可转债
		END AS CAP_TYPE
		,CASE
		WHEN T1.SEC_SORT =  110 THEN 'A股' --记账式企债
		WHEN T1.SEC_SORT = 120  THEN 'B股' --分离式可转债
		END AS SEC_SORT
        ,T3.SEC_MKT_LVL_SORT_NAME AS LSTN_BORD   --板块类型
        ,CASE WHEN K.SEC_CDE IS NOT NULL THEN '是' ELSE '否' END AS CSI_300
		,T1.BUY_AMT
		,T1.SAL_AMT
		,T1.TRAD_NET_AMT
		,T1.PSTN_VOL
		,T1.PSTN_MKT_VAL_ORIG_CRNC
FROM
(	SELECT	COALESCE(AA.STAT_DATE,BB.STAT_DATE) AS STAT_DATE
            ,COALESCE(AA.SEC_CDE,BB.SEC_CDE) AS SEC_CDE
			,COALESCE(AA.SEC_EXCH_CDE,BB.SEC_EXCH_CDE) AS SEC_EXCH_CDE
			,COALESCE(AA.STK_INVST_SORT,BB.STK_INVST_SORT) AS STK_INVST_SORT
			,COALESCE(AA.BNK_ID,BB.BNK_ID) AS BNK_ID
			,COALESCE(AA.SEC_SORT,BB.SEC_SORT) AS SEC_SORT
            ,COALESCE(AA.MKT_LVL_SORT,BB.MKT_LVL_SORT) AS MKT_LVL_SORT
			,AA.BUY_VOL
			,AA.BUY_AMT
			,AA.SAL_VOL
			,AA.SAL_AMT
			,AA.TRAD_NET_AMT
            ,BB.CAP_TYPE         --股本类型
			,BB.PSTN_VOL
			,BB.PSTN_MKT_VAL_ORIG_CRNC
	FROM
	(SELECT	A.STAT_DATE
            ,A.SEC_CDE
			,A.SEC_EXCH_CDE
			,A.STK_INVST_SORT
			,A.BNK_ID
			,A.SEC_CLSF AS SEC_SORT
            ,B.MKT_LVL_SORT
			,SUM(A.BUY_VOL) AS BUY_VOL
			,SUM(A.BUY_AMT) AS BUY_AMT
			,SUM(A.SAL_VOL) AS SAL_VOL
			,SUM(A.SAL_AMT) AS SAL_AMT
			,SUM(A.BUY_AMT - A.SAL_AMT) AS TRAD_NET_AMT
	FROM NSPUBVIEW.MID_INVST_SEC_TRAD A
	INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
	ON A.STAT_DATE <= B.S_DATE
	AND A.STAT_DATE > B.S_DATE
	AND A.SEC_CDE = B.SEC_CDE
	AND A.SEC_EXCH_CDE = B.MKT_SORT
	AND B.SEC_CTG IN ('11','12')
	GROUP BY 1,2,3,4,5,6,7
	) AA
	FULL JOIN
	(SELECT	A.STAT_DATE
                ,A.SEC_CDE
				,A.SEC_EXCH_CDE
				,A.STK_INVST_SORT
				,A.BNK_ID
				,A.SEC_CLSF AS SEC_SORT
                ,A.CAP_TYPE AS CAP_TYPE
                ,B.MKT_LVL_SORT
				,SUM(A.PSTN_VOL) AS PSTN_VOL
				,SUM(A.PSTN_MKT_VAL_ORIG_CRNC) AS PSTN_MKT_VAL_ORIG_CRNC
		FROM NSPUBVIEW.MID_INVST_SEC_PSTN A
		INNER JOIN NSOVIEW.CSDC_INTG_SEC_INFO B
		ON A.STAT_DATE <= B.S_DATE
		AND A.STAT_DATE > B.S_DATE
		AND A.SEC_CDE = B.SEC_CDE
		AND A.SEC_EXCH_CDE = B.MKT_SORT
		AND B.SEC_CTG IN ('11','12')
		GROUP BY 1,2,3,4,5,6,7,8
	) BB
	ON AA.STAT_DATE = BB.STAT_DATE
	AND AA.SEC_EXCH_CDE = BB.SEC_EXCH_CDE
	AND AA.STK_INVST_SORT = BB.STK_INVST_SORT
	AND AA.BNK_ID= BB.BNK_ID
	AND AA.SEC_SORT = BB.SEC_SORT
) T1
LEFT JOIN
(SELECT	CLSF_1
		,CLSF_2
		,CLSF_3
FROM NSPUBVIEW.CDE_STK_INVST_SORT
GROUP BY 1,2,3
) T2
ON T1.STK_INVST_SORT = T2.CLSF_3
LEFT JOIN CMSSVIEW.CDE_SEC_MKT_LVL_SORT T3                              --市场层次类别
ON  T1.MKT_LVL_SORT=T3.SEC_MKT_LVL_SORT_CDE
LEFT JOIN NSPVIEW.PRD_OBJ_STK_HIS K					--标的股历史表CSI_300
ON T1.SEC_CDE = K.SEC_CDE
AND T1.SEC_EXCH_CDE = K.SEC_EXCH_CDE
AND K.OBJ_TYPE = '007'
AND K.S_DATE <= T1.STAT_DATE
AND K.E_DATE > T1.STAT_DATE
;


COMMENT ON VIEW NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2 IS '分投资者类型股票交易持仓情况2';


COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.STAT_DATE IS '统计日期';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.SEC_CDE IS '证券代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.SEC_EXCH_CDE IS '证券交易所代码';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.STK_INVST_SORT_CLSF_1 IS '股票投资者类别（一级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.STK_INVST_SORT_CLSF_2 IS '股票投资者类别（二级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.STK_INVST_SORT_CLSF_3 IS '股票投资者类别（三级）';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.BNK_ID IS '银行标识';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.CAP_TYPE IS '股本类别';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.SEC_SORT IS '证券分类';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.LSTN_BORD  IS '板块类型';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.CSI_300 IS '证券是否是沪深300成分股';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.BUY_AMT  IS '买入金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.SAL_AMT IS '卖出金额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.TRAD_NET_AMT IS '买卖净额';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.PSTN_VOL IS '持仓数量';
COMMENT ON COLUMN NSSMSVIEW.SMS_QRY_2_INVST_STK_TRAD_PSTN_RPT_2.PSTN_MKT_VAL_ORIG_CRNC IS '持仓市值_原币';
